package com.wyjson.router.helper.group_new;

import android.content.Context;
import androidx.fragment.app.Fragment;
import com.wyjson.router.GoRouter;
import com.wyjson.router.model.Card;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER.
 * 参数片段
 * {@link com.wyjson.module_user.fragment.ParamFragment}
 */
public class NewParamFragmentGoRouter {
    public static String getPath() {
        return "/new/param/fragment";
    }

    public static Card build() {
        return GoRouter.getInstance().build(getPath());
    }

    public static Fragment go(Context context) {
        return (Fragment) build().go(context);
    }

    public static Builder get() {
        return new Builder();
    }

    public static Card build(int age, String name) {
        return get().setAge(age).setName(name).build();
    }

    public static Fragment go(Context context, int age, String name) {
        return (Fragment) build(age, name).go(context);
    }

    public static class Builder {
        private final Card mCard;

        public Builder() {
            mCard = GoRouter.getInstance().build(getPath());
        }

        public Builder setAge(int age) {
            mCard.withInt("age", age);
            return this;
        }

        public Builder setName(String name) {
            mCard.withString("name", name);
            return this;
        }

        public Card build() {
            return mCard;
        }
    }
}
