package com.wyjson.router.helper.module_main.group_main;

import androidx.annotation.Nullable;
import com.wyjson.router.GoRouter;
import com.wyjson.router.model.Card;
import com.wyjson.router.model.CardMeta;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER.
 * 事件页面
 * {@link com.wyjson.module_main.activity.EventActivity}
 */
public class MainEventActivityGoRouter {
    public static String getPath() {
        return "/main/event/activity";
    }

    @Nullable
    public static CardMeta getCardMeta() {
        return GoRouter.getInstance().build(getPath()).getCardMeta();
    }

    public static <T> void postEvent(T value) {
        GoRouter.getInstance().postEvent(getPath(), value);
    }

    public static Card build() {
        return GoRouter.getInstance().build(getPath());
    }

    public static void go() {
        build().go();
    }
}
