package com.wyjson.router.helper.module_user.group_user;

import android.content.Context;
import com.wyjson.router.GoRouter;
import com.wyjson.router.model.Card;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER.
 * 登录页面
 * {@link com.wyjson.module_user.activity.SignInActivity}
 */
public class UserSignInActivityGoRouter {
    public static String getPath() {
        return "/user/sign_in/activity";
    }

    public static Card build() {
        return GoRouter.getInstance().build(getPath());
    }

    public static void go(Context context) {
        build().go(context);
    }
}
