package com.wyjson.router.helper.module_user.group_user;

import android.content.Context;
import com.wyjson.router.GoRouter;
import com.wyjson.router.model.Card;
import com.wyjson.router.model.CardMeta;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER.
 * 用户信息页面
 * {@link com.wyjson.module_user.activity.UserInfoActivity}
 */
public class UserInfoActivityGoRouter {
    public static String getPath() {
        return "/user/info/activity";
    }

    public static CardMeta getCardMeta() {
        return GoRouter.getInstance().build(getPath()).getCardMeta();
    }

    public static <T> void postEvent(T value) {
        GoRouter.getInstance().postEvent(getPath(), value);
    }

    public static Card build() {
        return GoRouter.getInstance().build(getPath());
    }

    public static void go(Context context) {
        build().go(context);
    }
}
