package com.wyjson.router;

import android.content.Context;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import com.wyjson.module_common.route.service.user.PayService;
import com.wyjson.module_common.route.service.user.UserService;
import com.wyjson.router.model.Card;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER.
 */
public class GoRouterHelper {
    /**
     * 微信Pay服务
     * {@link com.wyjson.module_user.route.service.WechatPayServiceImpl}
     */
    @Nullable
    public static PayService getPayServiceForWechatPay() {
        return GoRouter.getInstance().getService(PayService.class, "WechatPay");
    }

    /**
     * 用户服务
     * {@link com.wyjson.module_user.route.service.UserServiceImpl}
     */
    @Nullable
    public static UserService getUserService() {
        return GoRouter.getInstance().getService(UserService.class);
    }

    /**
     * AliPay服务
     * {@link com.wyjson.module_user.route.service.AliPayServiceImpl}
     */
    @Nullable
    public static PayService getPayServiceForAlipay() {
        return GoRouter.getInstance().getService(PayService.class, "Alipay");
    }

    /**
     * Kotlin模块用户服务
     * {@link com.wyjson.module_kotlin.route.service.KotlinUserServiceImpl}
     */
    @Nullable
    public static UserService getUserServiceForKotlinUserService() {
        return GoRouter.getInstance().getService(UserService.class, "KotlinUserService");
    }

    /**
     * 参数页面 path
     * {@link com.wyjson.module_user.activity.ParamActivity}
     */
    public static String getParamActivityPath() {
        return "/new/param/activity";
    }

    /**
     * build 参数页面
     * {@link com.wyjson.module_user.activity.ParamActivity}
     */
    public static Card buildParamActivity(String nickname,
            com.wyjson.module_common.model.TestModel test) {
        return GoRouter.getInstance().build(getParamActivityPath())
                // 昵称
                .withString("nickname", nickname)
                // 自定义类型
                .withObject("test", test);
    }

    /**
     * go 参数页面
     * {@link com.wyjson.module_user.activity.ParamActivity}
     */
    public static void goParamActivity(Context context, String nickname,
            com.wyjson.module_common.model.TestModel test) {
        buildParamActivity(nickname, test).go(context);
    }

    /**
     * build 参数页面
     * {@link com.wyjson.module_user.activity.ParamActivity}
     */
    public static Card buildParamActivity(String nickname,
            com.wyjson.module_common.model.TestModel test, int base, int age) {
        return GoRouter.getInstance().build(getParamActivityPath())
                // 昵称
                .withString("nickname", nickname)
                // 自定义类型
                .withObject("test", test)
                // 我是一个父类字段
                .withInt("base", base)
                .withInt("age", age);
    }

    /**
     * go 参数页面
     * {@link com.wyjson.module_user.activity.ParamActivity}
     */
    public static void goParamActivity(Context context, String nickname,
            com.wyjson.module_common.model.TestModel test, int base, int age) {
        buildParamActivity(nickname, test, base, age).go(context);
    }

    /**
     * 参数片段 path
     * {@link com.wyjson.module_user.fragment.ParamFragment}
     */
    public static String getParamFragmentPath() {
        return "/new/param/fragment";
    }

    /**
     * build 参数片段
     * {@link com.wyjson.module_user.fragment.ParamFragment}
     */
    public static Card buildParamFragment() {
        return GoRouter.getInstance().build(getParamFragmentPath());
    }

    /**
     * go 参数片段
     * {@link com.wyjson.module_user.fragment.ParamFragment}
     */
    public static Fragment goParamFragment(Context context) {
        return (Fragment) buildParamFragment().go(context);
    }

    /**
     * build 参数片段
     * {@link com.wyjson.module_user.fragment.ParamFragment}
     */
    public static Card buildParamFragment(int age, String name) {
        return GoRouter.getInstance().build(getParamFragmentPath())
                .withInt("age", age)
                .withString("name", name);
    }

    /**
     * go 参数片段
     * {@link com.wyjson.module_user.fragment.ParamFragment}
     */
    public static Fragment goParamFragment(Context context, int age, String name) {
        return (Fragment) buildParamFragment(age, name).go(context);
    }

    /**
     * 这是一个kotlin页面，本库支持kapt path
     * {@link com.wyjson.module_kotlin.activity.KotlinActivity}
     */
    public static String getKotlinActivityPath() {
        return "/kotlin/activity";
    }

    /**
     * build 这是一个kotlin页面，本库支持kapt
     * {@link com.wyjson.module_kotlin.activity.KotlinActivity}
     */
    public static Card buildKotlinActivity(String nickname) {
        return GoRouter.getInstance().build(getKotlinActivityPath())
                // 昵称
                .withString("nickname", nickname);
    }

    /**
     * go 这是一个kotlin页面，本库支持kapt
     * {@link com.wyjson.module_kotlin.activity.KotlinActivity}
     */
    public static void goKotlinActivity(Context context, String nickname) {
        buildKotlinActivity(nickname).go(context);
    }

    /**
     * build 这是一个kotlin页面，本库支持kapt
     * {@link com.wyjson.module_kotlin.activity.KotlinActivity}
     */
    public static Card buildKotlinActivity(String nickname, int age) {
        return GoRouter.getInstance().build(getKotlinActivityPath())
                // 昵称
                .withString("nickname", nickname)
                .withInt("age", age);
    }

    /**
     * go 这是一个kotlin页面，本库支持kapt
     * {@link com.wyjson.module_kotlin.activity.KotlinActivity}
     */
    public static void goKotlinActivity(Context context, String nickname, int age) {
        buildKotlinActivity(nickname, age).go(context);
    }

    /**
     * 主页 path
     * {@link com.wyjson.module_main.activity.MainActivity}
     */
    public static String getMainActivityPath() {
        return "/main/activity";
    }

    /**
     * build 主页
     * {@link com.wyjson.module_main.activity.MainActivity}
     */
    public static Card buildMainActivity() {
        return GoRouter.getInstance().build(getMainActivityPath());
    }

    /**
     * go 主页
     * {@link com.wyjson.module_main.activity.MainActivity}
     */
    public static void goMainActivity(Context context) {
        buildMainActivity().go(context);
    }

    /**
     * 事件页面 path
     * {@link com.wyjson.module_main.activity.EventActivity}
     */
    public static String getEventActivityPath() {
        return "/main/event/activity";
    }

    /**
     * build 事件页面
     * {@link com.wyjson.module_main.activity.EventActivity}
     */
    public static Card buildEventActivity() {
        return GoRouter.getInstance().build(getEventActivityPath());
    }

    /**
     * go 事件页面
     * {@link com.wyjson.module_main.activity.EventActivity}
     */
    public static void goEventActivity(Context context) {
        buildEventActivity().go(context);
    }

    /**
     * 事件片段 path
     * {@link com.wyjson.module_main.fragment.EventFragment}
     */
    public static String getEventFragmentPath() {
        return "/main/event/fragment";
    }

    /**
     * build 事件片段
     * {@link com.wyjson.module_main.fragment.EventFragment}
     */
    public static Card buildEventFragment() {
        return GoRouter.getInstance().build(getEventFragmentPath());
    }

    /**
     * go 事件片段
     * {@link com.wyjson.module_main.fragment.EventFragment}
     */
    public static Fragment goEventFragment(Context context) {
        return (Fragment) buildEventFragment().go(context);
    }

    /**
     * 欢迎页 path
     * {@link com.wyjson.module_main.activity.SplashActivity}
     */
    public static String getSplashActivityPath() {
        return "/main/splash/activity";
    }

    /**
     * build 欢迎页
     * {@link com.wyjson.module_main.activity.SplashActivity}
     */
    public static Card buildSplashActivity() {
        return GoRouter.getInstance().build(getSplashActivityPath());
    }

    /**
     * go 欢迎页
     * {@link com.wyjson.module_main.activity.SplashActivity}
     */
    public static void goSplashActivity(Context context) {
        buildSplashActivity().go(context);
    }

    /**
     * 卡片片段 path
     * {@link com.wyjson.module_user.fragment.CardFragment}
     */
    public static String getCardFragmentPath() {
        return "/user/card/fragment";
    }

    /**
     * build 卡片片段
     * {@link com.wyjson.module_user.fragment.CardFragment}
     */
    public static Card buildCardFragment() {
        return GoRouter.getInstance().build(getCardFragmentPath());
    }

    /**
     * go 卡片片段
     * {@link com.wyjson.module_user.fragment.CardFragment}
     */
    public static Fragment goCardFragment(Context context) {
        return (Fragment) buildCardFragment().go(context);
    }

    /**
     * 用户信息页面 path
     * {@link com.wyjson.module_user.activity.UserInfoActivity}
     */
    public static String getUserInfoActivityPath() {
        return "/user/info/activity";
    }

    /**
     * build 用户信息页面
     * {@link com.wyjson.module_user.activity.UserInfoActivity}
     */
    public static Card buildUserInfoActivity() {
        return GoRouter.getInstance().build(getUserInfoActivityPath());
    }

    /**
     * go 用户信息页面
     * {@link com.wyjson.module_user.activity.UserInfoActivity}
     */
    public static void goUserInfoActivity(Context context) {
        buildUserInfoActivity().go(context);
    }

    /**
     * 登录页面 path
     * {@link com.wyjson.module_user.activity.SignInActivity}
     */
    public static String getSignInActivityPath() {
        return "/user/sign_in/activity";
    }

    /**
     * build 登录页面
     * {@link com.wyjson.module_user.activity.SignInActivity}
     */
    public static Card buildSignInActivity() {
        return GoRouter.getInstance().build(getSignInActivityPath());
    }

    /**
     * go 登录页面
     * {@link com.wyjson.module_user.activity.SignInActivity}
     */
    public static void goSignInActivity(Context context) {
        buildSignInActivity().go(context);
    }
}
