package com.wyjson.router.helper.service;

import androidx.annotation.Nullable;
import com.wyjson.module_common.route.service.user.PayService;
import com.wyjson.router.GoRouter;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER.
 * AliPay服务
 * {@link com.wyjson.module_user.route.service.AliPayServiceImpl}
 */
public class PayServiceForAlipayGoRouter {
    @Nullable
    public static PayService get() {
        return GoRouter.getInstance().getService(PayService.class, "Alipay");
    }
}
