package com.wyjson.router.helper.module_kotlin.group_kotlin;

import androidx.annotation.Nullable;
import com.wyjson.router.GoRouter;
import com.wyjson.router.model.Card;
import com.wyjson.router.model.CardMeta;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER.
 * 这是一个kotlin页面，本库支持kapt
 * {@link com.wyjson.module_kotlin.activity.KotlinActivity}
 */
public class KotlinActivityGoRouter {
    public static String getPath() {
        return "/kotlin/activity";
    }

    @Nullable
    public static CardMeta getCardMeta() {
        return GoRouter.getInstance().build(getPath()).getCardMeta();
    }

    public static <T> void postEvent(T value) {
        GoRouter.getInstance().postEvent(getPath(), value);
    }

    public static Card build(String nickname) {
        return GoRouter.getInstance().build(getPath())
                // 昵称
                .withString("nickname", nickname);
    }

    public static void go(String nickname) {
        build(nickname).go();
    }

    public static Builder create(String nickname) {
        return new Builder(nickname);
    }

    public static Card build(String nickname, int age) {
        return create(nickname).setAge(age).build();
    }

    public static void go(String nickname, int age) {
        build(nickname, age).go();
    }

    public static class Builder {
        private final Card mCard;

        public Builder(String nickname) {
            mCard = GoRouter.getInstance().build(getPath())
                    // 昵称
                    .withString("nickname", nickname);
        }

        public Builder setAge(int age) {
            mCard.withInt("age", age);
            return this;
        }

        public Card build() {
            return mCard;
        }
    }
}
