package com.wyjson.router.helper.module_kotlin.group_kotlin;

import android.content.Context;
import com.wyjson.router.GoRouter;
import com.wyjson.router.model.Card;
import java.lang.String;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER.
 * 这是一个kotlin页面，本库支持kapt
 * {@link com.wyjson.module_kotlin.activity.KotlinActivity}
 */
public class KotlinActivityGoRouter {
    public static String getPath() {
        return "/kotlin/activity";
    }

    public static Card build(String nickname) {
        return GoRouter.getInstance().build(getPath())
                // 昵称
                .withString("nickname", nickname);
    }

    public static void go(Context context, String nickname) {
        build(nickname).go(context);
    }

    public static Builder get(String nickname) {
        return new Builder(nickname);
    }

    public static Card build(String nickname, int age) {
        return get(nickname).setAge(age).build();
    }

    public static void go(Context context, String nickname, int age) {
        build(nickname, age).go(context);
    }

    public static class Builder {
        private final Card mCard;

        public Builder(String nickname) {
            mCard = GoRouter.getInstance().build(getPath())
                    // 昵称
                    .withString("nickname", nickname);
        }

        public Builder setAge(int age) {
            mCard.withInt("age", age);
            return this;
        }

        public Card build() {
            return mCard;
        }
    }
}
