package com.wyjson.router.compiler.utils;

public class Consts {
    // Generate
    public static final String PROJECT = "GoRouter";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER.";
    public static final String METHOD_LOAD_INTO = "loadInto";

    // System interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "androidx.fragment.app.Fragment";

    public static final String PACKAGE_NAME = "com.wyjson.router";
    public static final String MODULE_PACKAGE_NAME = PACKAGE_NAME + ".module";
    public static final String GOROUTER_PACKAGE_NAME = PACKAGE_NAME + ".core.GoRouter";

    // Log
    public static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";
    public static final String NO_MODULE_NAME_TIPS = "These no module name, at 'build.gradle', like :\n" +
            "android {\n" +
            "    defaultConfig {\n" +
            "        ...\n" +
            "        javaCompileOptions {\n" +
            "            annotationProcessorOptions {\n" +
            "                arguments = [GOROUTER_MODULE_NAME: project.getName()]\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "}\n";

    // Options of processor
    public static final String KEY_MODULE_NAME = "GOROUTER_MODULE_NAME";

    // Annotation type
    public static final String ANNOTATION_TYPE_SERVICE = "com.wyjson.router.annotation.Service";
    public static final String ANNOTATION_TYPE_INTERCEPTOR = "com.wyjson.router.annotation.Interceptor";
    public static final String ANNOTATION_TYPE_ROUTE = "com.wyjson.router.annotation.Route";
    public static final String ANNOTATION_TYPE_PARAM = "com.wyjson.router.annotation.Param";
}