package com.wyjson.router.gradle_plugin.utils

object Constants {
    const val GENERATE_ROUTE_DOC = "generateRouteDoc";
    const val QUICK_GENERATE_ROUTE_DOC = "quickGenerateRouteDoc";
    const val ASSEMBLE_ROUTE_MODULE_TASK = "AssembleRouteModuleTask";
    const val ASSEMBLE_APPLICATION_MODULE_TASK = "AssembleApplicationModuleTask";
    const val GENERATE_GOROUTER_HELPER_TASK = "GenerateGoRouterHelperTask";

    private const val SEPARATOR = "$$";
    const val PACKAGE_NAME = "com.wyjson.router"

    const val PROJECT = "GoRouter";
    const val DOCUMENT_FILE_NAME = "route-doc.json"
    const val _CLASS = ".class"

    // 路由注册生成类名后缀$$Route
    const val ROUTE_MODULE_NAME_SUFFIX = SEPARATOR + "Route"

    // 需要扫描注入的类,所在的包名
    const val ROUTE_MODULE_SCAN_TARGET_INJECT_PACKAGE_NAME = "$PACKAGE_NAME.module.route"

    // 注入到这个类下
    const val ROUTE_MODULE_INJECT_CLASS_NAME = "$PACKAGE_NAME.core.RouteModuleCenter"

    // 注入到这个方法
    const val ROUTE_MODULE_INJECT_METHOD_NAME = "loadByPlugin"

    // 注入内容方法名
    const val ROUTE_MODULE_INJECT_TARGET_METHOD_NAME = "register"


    /**
     * application module
     */

    // application module生成的代理类名后缀$$AP
    const val APPLICATION_MODULE_NAME_SUFFIX = SEPARATOR + "AP"

    // 需要扫描注入的类,所在的包名
    const val APPLICATION_MODULE_SCAN_TARGET_INJECT_PACKAGE_NAME = "$PACKAGE_NAME.module.application"

    // 注入到这个类下
    const val APPLICATION_MODULE_INJECT_CLASS_NAME = "$PACKAGE_NAME.core.ApplicationModuleCenter"

    // 注入到这个方法
    const val APPLICATION_MODULE_INJECT_METHOD_NAME = "loadByPlugin"

    // 注入内容方法名
    const val APPLICATION_MODULE_INJECT_TARGET_METHOD_NAME = "register"


    fun dotToSlash(str: String): String {
        return str.replace(".", "/")
    }

    fun slashToDot(str: String): String {
        return str.replace("/", ".")
    }


    /**
     * GoRouterHelper
     */
    const val WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY GOROUTER."
    const val GOROUTER_HELPER_CLASS_NAME = "GoRouterHelper"
    const val FRAGMENT = "androidx.fragment.app.Fragment"
    const val NULLABLE = "androidx.annotation.Nullable"
    const val CARD = "com.wyjson.router.model.Card"

    // Java type
    private const val LANG = "java.lang"
    const val BYTE_PACKAGE = "$LANG.Byte"
    const val SHORT_PACKAGE = "$LANG.Short"
    const val INTEGER_PACKAGE = "$LANG.Integer"
    const val LONG_PACKAGE = "$LANG.Long"
    const val FLOAT_PACKAGE = "$LANG.Float"
    const val DOUBLE_PACKAGE = "$LANG.Double"
    const val BOOLEAN_PACKAGE = "$LANG.Boolean"
    const val CHAR_PACKAGE = "$LANG.Character"
    const val STRING_PACKAGE = "$LANG.String"
    const val SERIALIZABLE_PACKAGE = "java.io.Serializable"
    const val PARCELABLE_PACKAGE = "android.os.Parcelable"

    const val BYTE_PRIMITIVE = "byte"
    const val SHORT_PRIMITIVE = "short"
    const val INTEGER_PRIMITIVE = "int"
    const val LONG_PRIMITIVE = "long"
    const val FLOAT_PRIMITIVE = "float"
    const val DOUBLE_PRIMITIVE = "double"
    const val BOOLEAN_PRIMITIVE = "boolean"
    const val CHAR_PRIMITIVE = "char"
}